DNA = "CTTAGAGGATCGGGCCTTTAATGCTGGCAAGGGGTCCATTTTGGTTTTTGTTAGTCCGTCATGCGCAGATGTACACGAGAACTACGGCTTTTGTTAGACTGCTCGGTAATAGAGATTAGAGATCAATGCTACGTCAAACAGTGACATTCGCAGCGCGGGGCATGTCCAAGCCTAGCGGCCCAAATCCAATATCACCCAGCCTAATTGTGGGACCATGTTGAGTGTACCTGTGGAGATGCTCGTGATCAGCCCTCCCGTTATCTCCCATACAATTGGCCTTAGCTGCCATTTATACAATTTCGGAGTATTGGCTTAATTTCGGTGTAATCGGTAAGCCGCTTCCGGGGGCACGGGCCATTGCCGCCCTCTTTTTTTTTAGAATTCTATACCTGAATTGCCGGTGTATGTGTGTCGACTTAGAAGGCATTCCAAAAGCATGGACTCGAGTAGGTGCCTGTGCACGAATAGGACAATTCCTTCGCCAGCAGGGATGGGCCTCCCCGAGTATTACGAAAGATCGTGTTCTCTGTAGGACGGAACACAGACCCCCAACGCACCGAGCATCCCGACTCTCTGTTGTGTCGATGAAATTGAGATTACCATACGCGTGGCTAAATGGAGTCGACATCATTACTTAGGTTGGCTGACTAAGGCGCCCCGCGACCGATACGCACATCAGCTCTCACGCCTGGTATGGCCTTCAGTCTTAAACCAATTAGTCTAGCACTCTTGATGGCCCAGCCGCGAAGTGGGGTACCTCCTTCGGATGCCGTACAAACACACTCGTTTGATGTCGAATCCGTCTGTTCAGAGGGTCCCACCCAGAGATCTGAGGATGTCGCGTTGGTCCAAATCAGACGGCCAAGACGACCATGACAGGTCGTGGTCCGCAGTTCCGGTACACCGGGCGATCGATTACATTCTCCATGATTCCAGGTCTAATGGCCCGGAAGGGCCATGGTTA"

Acount = 0
Ccount = 0
Gcount = 0
Tcount = 0

for base in DNA:
    if base == "A":
        Acount += 1
    if base == "C":
        Ccount += 1
    if base == "G":
        Gcount += 1
    if base == "T":
        Tcount += 1

print(Acount, Ccount, Gcount, Tcount)