"""
Want to make a point that the question stated that they would give you at most 10 DNA strings
it takes time copying and pasting the DNA strings over and I got very lucky
Moving forward if any similar questions arises I'll be reading in the file instead
but I won't add the dataset file into this repo
"""


DNA = "CCCATGGACAAAAGATGACGGGTACTACACAGGGAGACATGCCAGCCGGAGCTCTTCGTATTACGTTAGCCGCATCCTCTAGTTGGCAGCGCGGGCGGGTCTTCCCGGGCATTTTGAGCTTAATTATAGCGTAGATGTTTCGGTCATGGTTTAAGGTAGGCAAATGGGAGGTAGCAAGGCCGGCCTCATAGTAGAACTACATGTGACAGGCAACCGGGCCCATTGGAGTTTCCTCCTTCGGGTGAGAGGAGAATATATCTAAAACGCTTACATGCAAAATGGCAAGCAAGGCGCCTGCAAGGTGGCGTCAACGTGGGCTAGTCTTTTTTGACAAGCCCGTCGTAGGGCGCCGAGAATTAAGTAAATTCTACGAGTAACACGAAGCCGAAAGATCTGGATTAGCTGGATACGGGCCCTTTCGAGTCGGGCAAATAGGCCACGCCTGTCACAGCTCGGACCGGTTCCCTCGCCCTCACTAGCGTAACTAACACCACGAGAGAGAGCCTTGTTGTCTTTTACAGGTAGATGACTCCGATAAGAATCTTCTCCCGTCTCTCTTTACCGATGAGAGGGTCTCGAACCTGACCGCGGTCGATTCAATGAGCCAAGCATCCCTTATGGATGGTAGATTATGCGTATTTTACGGACGTTACATTAGGTTGGAATATTGTATCGACTGTCTCACATCCGCGCCAACATGGAGATACCAATGCGAGAACTGCCACCTGCCCCGAAACACGTCGCACTACCCGAGCGAGCATGCCAGGATTGTAGCTTCACCACCACACGGCCCCAAGCGCTGCAATCTGCATTGGTGAGCACTCATCAATTAAACATGCGGTGAATGGCTTATGTGTTTACATTTGTTACAGACCAAGGAAATCCACTAACGC"

total_bases = len(DNA)
GCcount = 0

for base in DNA:
    if base in ["G", "C"]:
        GCcount += 1

percentage = (GCcount / total_bases) * 100
print(f"{percentage:6f}")