DNA = "TGCCCATAACCCTGGGGCGCCATTCCCCCAGAGAGGCCGGCTCCTTGAGTGTCGGGTCACCAGGCTGCCTTGTATCTGGTGGAAGTGACGGCCACGGGAATGGAGACACGGTCGATCTGTAACCCTTGGTTAGAAGGTTGCCAACTTATACGGATTAGCTATTCGCTATGCGTGATATCGAGTCCATCTCGGCCAACTCACTGATGTTACCACTCTACTCTCGAGTCCTAACATACTGTCTAAACAGAATAGGGCGACCAGAAGCTCATTGTAATCTCGGCATTTGGTCCGTAAACGCGCCGCCATTACCACGTGACTATGGTCCGCAAGAAAGGTGTGCTCCCGACAGCTTTGTCTAAACGACCAGTTTTATTGTTTTGGTAGTCCTTTACGCTTGAGCGCAGTGTCGTAATACAGTTCTATCGGCAGAGGTTTTCGTTTGGGAGCCAGGCTCCAAGTGACTCGTTTTACATCCTCGAATCCAGCGCCCCACTCACAGTGGTGTCTGCATACCGTAGTGGCGACACTAACTCCAGCGAGCACTTTATGGACATTTCGGCTACTGACCACATGTGCGTTAAACCGGCTCCGGATCAAGATAGACGACTTGTACCGCTTGGGGGATAAGAATGGGTCATATTGTAGGGGGGGGCCGCTTCGGAAATTTGCGCTAGCAAGGCATGGAGTCTGTCGGAAGCCTGTGATGCTCATTGCGTCTAAGCCTGATGCCTTTAGAGTAAATTCGGTAATGCACGGGAATGCTGGACTCGTACGACGCGGTGCTTCGGTCCCAACTACGTTGTTGCGCGCCCTTGTGTTCAAGGTTAAACACCGTTAGGAGCAGGGTAGACCAGAGATACTTGGCGACGTCTGCCGTCAGAAGTGTAGGCAAACAGATTACTCCGGCGCACCCCGGCTTCGGAAGACGTCAC"
complement = ""
for base in DNA:
    if base == "A":
        complement  += "T"
    if base == "T":
        complement += "A"
    if base == "C":
        complement += "G"
    if base == "G":
        complement += "C"

print(complement[::-1]) # reverse as complement runs in opposite direction